#!/usr/bin/env bash
#
# add-gemini-aliases.sh - Adds gemini-env and gemini-profile aliases to user's .zshrc
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
GEMINI_ENV_PATH="${SCRIPT_DIR}/gemini-env.sh"
GEMINI_PROFILE_PATH="${SCRIPT_DIR}/gemini-profile.sh"

ZSHRC="${HOME}/.zshrc"

ALIAS_BLOCK_START="# >>> Gemini Code multi-account aliases >>>"
ALIAS_BLOCK_END="# <<< Gemini Code multi-account aliases <<<"

# Check if scripts exist
if [ ! -f "$GEMINI_ENV_PATH" ]; then
    echo "❌ Error: gemini-env.sh not found at $GEMINI_ENV_PATH"
    exit 1
fi

if [ ! -f "$GEMINI_PROFILE_PATH" ]; then
    echo "❌ Error: gemini-profile.sh not found at $GEMINI_PROFILE_PATH"
    exit 1
fi

# Generate alias block
generate_aliases() {
    cat <<ALIASES
$ALIAS_BLOCK_START
# Gemini Code multi-account management aliases
# Auto-generated by add-gemini-aliases.sh

# gemini-env.sh aliases (environment-based switching)
alias ge="$GEMINI_ENV_PATH"
alias gel="$GEMINI_ENV_PATH list"
alias gec="$GEMINI_ENV_PATH create"
alias gee="$GEMINI_ENV_PATH edit"
alias ges="$GEMINI_ENV_PATH show"
alias gev="$GEMINI_ENV_PATH validate"

# gemini-profile.sh aliases (full profile rotation)
alias gp="$GEMINI_PROFILE_PATH"
alias gpl="$GEMINI_PROFILE_PATH list"
alias gpc="$GEMINI_PROFILE_PATH create"
alias gps="$GEMINI_PROFILE_PATH switch"
alias gpcurrent="$GEMINI_PROFILE_PATH current"
alias gpedit="$GEMINI_PROFILE_PATH edit"

# Quick run with specific accounts
alias gem-work="$GEMINI_ENV_PATH work gemini"
alias gem-personal="$GEMINI_ENV_PATH personal gemini"

$ALIAS_BLOCK_END
ALIASES
}

# Check if already exists
if grep -q "$ALIAS_BLOCK_START" "$ZSHRC" 2>/dev/null; then
    echo "⚠ Aliases already exist in $ZSHRC"
    echo "Do you want to update them? [y/N] "
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi

    # Remove existing block
    if command -v sed &>/dev/null; then
        sed -i.bak "/$ALIAS_BLOCK_START/,/$ALIAS_BLOCK_END/d" "$ZSHRC"
        rm -f "${ZSHRC}.bak" 2>/dev/null || true
        echo "✅ Removed old aliases"
    fi
fi

# Add new block
echo "" >> "$ZSHRC"
generate_aliases >> "$ZSHRC"

echo ""
echo "✅ Added Gemini Code aliases to $ZSHRC"
echo ""
echo "To use immediately, run:"
echo "  source ~/.zshrc"
echo ""
echo "Available aliases:"
echo "  ge          gemini-env.sh (all commands)"
echo "  gp          gemini-profile.sh (all commands)"
echo ""
echo "For full list see: $ZSHRC"
