#!/usr/bin/env bash
#
# add-claude-aliases.sh - Adds claude-env and claude-profile aliases to user's .zshrc
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
CLAUDE_ENV_PATH="${SCRIPT_DIR}/claude-env.sh"
CLAUDE_PROFILE_PATH="${SCRIPT_DIR}/claude-profile.sh"

ZSHRC="${HOME}/.zshrc"

ALIAS_BLOCK_START="# >>> Claude Code multi-account aliases >>>"
ALIAS_BLOCK_END="# <<< Claude Code multi-account aliases <<<"

# Check if scripts exist
if [ ! -f "$CLAUDE_ENV_PATH" ]; then
    echo "❌ Error: claude-env.sh not found at $CLAUDE_ENV_PATH"
    exit 1
fi

if [ ! -f "$CLAUDE_PROFILE_PATH" ]; then
    echo "❌ Error: claude-profile.sh not found at $CLAUDE_PROFILE_PATH"
    exit 1
fi

# Generate alias block
generate_aliases() {
    cat <<ALIASES
$ALIAS_BLOCK_START
# Claude Code multi-account management aliases
# Auto-generated by add-claude-aliases.sh

# claude-env.sh aliases (environment-based switching)
alias ce="$CLAUDE_ENV_PATH"
alias cel="$CLAUDE_ENV_PATH list"
alias cec="$CLAUDE_ENV_PATH create"
alias cee="$CLAUDE_ENV_PATH edit"
alias ces="$CLAUDE_ENV_PATH show"
alias cev="$CLAUDE_ENV_PATH validate"

# claude-profile.sh aliases (full profile rotation)
alias cp="$CLAUDE_PROFILE_PATH"
alias cpl="$CLAUDE_PROFILE_PATH list"
alias cpc="$CLAUDE_PROFILE_PATH create"
alias cps="$CLAUDE_PROFILE_PATH switch"
alias cpcurrent="$CLAUDE_PROFILE_PATH current"
alias cpedit="$CLAUDE_PROFILE_PATH edit"

# Quick run with specific accounts
alias c-work="$CLAUDE_ENV_PATH work claude"
alias c-personal="$CLAUDE_ENV_PATH personal claude"

$ALIAS_BLOCK_END
ALIASES
}

# Check if already exists
if grep -q "$ALIAS_BLOCK_START" "$ZSHRC" 2>/dev/null; then
    echo "⚠ Aliases already exist in $ZSHRC"
    echo "Do you want to update them? [y/N] "
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi

    # Remove existing block
    if command -v sed &>/dev/null; then
        sed -i.bak "/$ALIAS_BLOCK_START/,/$ALIAS_BLOCK_END/d" "$ZSHRC"
        rm -f "${ZSHRC}.bak" 2>/dev/null || true
        echo "✅ Removed old aliases"
    fi
fi

# Add new block
echo "" >> "$ZSHRC"
generate_aliases >> "$ZSHRC"

echo ""
echo "✅ Added Claude Code aliases to $ZSHRC"
echo ""
echo "To use immediately, run:"
echo "  source ~/.zshrc"
echo ""
echo "Available aliases:"
echo "  ce          claude-env.sh (all commands)"
echo "  cp          claude-profile.sh (all commands)"
echo ""
echo "For full list see: $ZSHRC"
