#!/usr/bin/env bash
#
# add-qwen-aliases.sh - Adds qwen-env and qwen-profile aliases to user's .zshrc
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
QWEN_ENV_PATH="${SCRIPT_DIR}/qwen-env.sh"
QWEN_PROFILE_PATH="${SCRIPT_DIR}/qwen-profile.sh"

ZSHRC="${HOME}/.zshrc"

ALIAS_BLOCK_START="# >>> Qwen Code multi-account aliases >>>"
ALIAS_BLOCK_END="# <<< Qwen Code multi-account aliases <<<"

# Check if scripts exist
if [ ! -f "$QWEN_ENV_PATH" ]; then
    echo "❌ Error: qwen-env.sh not found at $QWEN_ENV_PATH"
    exit 1
fi

if [ ! -f "$QWEN_PROFILE_PATH" ]; then
    echo "❌ Error: qwen-profile.sh not found at $QWEN_PROFILE_PATH"
    exit 1
fi

# Generate alias block
generate_aliases() {
    cat <<ALIASES
$ALIAS_BLOCK_START
# Qwen Code multi-account management aliases
# Auto-generated by add-qwen-aliases.sh

# qwen-env.sh aliases (environment-based switching)
alias qe="$QWEN_ENV_PATH"
alias qel="$QWEN_ENV_PATH list"
alias qec="$QWEN_ENV_PATH create"
alias qee="$QWEN_ENV_PATH edit"
alias qes="$QWEN_ENV_PATH show"
alias qev="$QWEN_ENV_PATH validate"

# OAuth switching aliases
alias qeol="$QWEN_ENV_PATH oauth-list"
alias qeoc="$QWEN_ENV_PATH oauth-create"
alias qeos="$QWEN_ENV_PATH oauth-switch"
alias qeocurrent="$QWEN_ENV_PATH oauth-current"
alias qeologin="$QWEN_ENV_PATH oauth-login"

# qwen-profile.sh aliases (full profile rotation)
alias qp="$QWEN_PROFILE_PATH"
alias qpl="$QWEN_PROFILE_PATH list"
alias qpc="$QWEN_PROFILE_PATH create"
alias qps="$QWEN_PROFILE_PATH switch"
alias qpcurrent="$QWEN_PROFILE_PATH current"
alias qpedit="$QWEN_PROFILE_PATH edit"

# Quick run with specific accounts
alias qw-work="$QWEN_ENV_PATH work qwen"
alias qw-personal="$QWEN_ENV_PATH personal qwen"

$ALIAS_BLOCK_END
ALIASES
}

# Check if already exists
if grep -q "$ALIAS_BLOCK_START" "$ZSHRC" 2>/dev/null; then
    echo "⚠ Aliases already exist in $ZSHRC"
    echo "Do you want to update them? [y/N] "
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi

    # Remove existing block
    if command -v sed &>/dev/null; then
        sed -i.bak "/$ALIAS_BLOCK_START/,/$ALIAS_BLOCK_END/d" "$ZSHRC"
        rm -f "${ZSHRC}.bak" 2>/dev/null || true
        echo "✅ Removed old aliases"
    fi
fi

# Add new block
echo "" >> "$ZSHRC"
generate_aliases >> "$ZSHRC"

echo ""
echo "✅ Added Qwen Code aliases to $ZSHRC"
echo ""
echo "To use immediately, run:"
echo "  source ~/.zshrc"
echo ""
echo "Available aliases:"
echo "  qe          qwen-env.sh (all commands)"
echo "  qeol        list OAuth accounts"
echo "  qeos <name> switch OAuth account"
echo "  qp          qwen-profile.sh (all commands)"
echo ""
echo "For full list see: $ZSHRC"
