#!/usr/bin/env bash
#
# add-kilo-aliases.sh - Adds kilo-env and kilo-profile aliases to user's .zshrc
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
KILO_ENV_PATH="${SCRIPT_DIR}/kilo-env.sh"
KILO_PROFILE_PATH="${SCRIPT_DIR}/kilo-profile.sh"

ZSHRC="${HOME}/.zshrc"

ALIAS_BLOCK_START="# >>> Kilo AI multi-account aliases >>>"
ALIAS_BLOCK_END="# <<< Kilo AI multi-account aliases <<<"

# Check if scripts exist
if [ ! -f "$KILO_ENV_PATH" ]; then
    echo "❌ Error: kilo-env.sh not found at $KILO_ENV_PATH"
    exit 1
fi

if [ ! -f "$KILO_PROFILE_PATH" ]; then
    echo "❌ Error: kilo-profile.sh not found at $KILO_PROFILE_PATH"
    exit 1
fi

# Generate alias block
generate_aliases() {
    cat <<ALIASES
$ALIAS_BLOCK_START
# Kilo AI multi-account management aliases
# Auto-generated by add-kilo-aliases.sh

# kilo-env.sh aliases (environment-based switching)
alias ke="$KILO_ENV_PATH"
alias kel="$KILO_ENV_PATH list"
alias kec="$KILO_ENV_PATH create"
alias kee="$KILO_ENV_PATH edit"
alias kes="$KILO_ENV_PATH show"
alias kev="$KILO_ENV_PATH validate"

# kilo-profile.sh aliases (full profile rotation)
alias kp="$KILO_PROFILE_PATH"
alias kpl="$KILO_PROFILE_PATH list"
alias kpc="$KILO_PROFILE_PATH create"
alias kps="$KILO_PROFILE_PATH switch"
alias kpcurrent="$KILO_PROFILE_PATH current"
alias kpedit="$KILO_PROFILE_PATH edit"

# Quick run with specific accounts
alias k-work="$KILO_ENV_PATH work kilo"
alias k-personal="$KILO_ENV_PATH personal kilo"

$ALIAS_BLOCK_END
ALIASES
}

# Check if already exists
if grep -q "$ALIAS_BLOCK_START" "$ZSHRC" 2>/dev/null; then
    echo "⚠ Aliases already exist in $ZSHRC"
    echo "Do you want to update them? [y/N] "
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi

    # Remove existing block
    if command -v sed &>/dev/null; then
        sed -i.bak "/$ALIAS_BLOCK_START/,/$ALIAS_BLOCK_END/d" "$ZSHRC"
        rm -f "${ZSHRC}.bak" 2>/dev/null || true
        echo "✅ Removed old aliases"
    fi
fi

# Add new block
echo "" >> "$ZSHRC"
generate_aliases >> "$ZSHRC"

echo ""
echo "✅ Added Kilo AI aliases to $ZSHRC"
echo ""
echo "To use immediately, run:"
echo "  source ~/.zshrc"
echo ""
echo "Available aliases:"
echo "  ke          kilo-env.sh (all commands)"
echo "  kp          kilo-profile.sh (all commands)"
echo ""
echo "For full list see: $ZSHRC"
