#!/usr/bin/env bash
#
# add-opencode-aliases.sh - Adds opencode-env and opencode-profile aliases to user's .zshrc
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
OPENCODE_ENV_PATH="${SCRIPT_DIR}/opencode-env.sh"
OPENCODE_PROFILE_PATH="${SCRIPT_DIR}/opencode-profile.sh"

ZSHRC="${HOME}/.zshrc"

ALIAS_BLOCK_START="# >>> OpenCode multi-account aliases >>>"
ALIAS_BLOCK_END="# <<< OpenCode multi-account aliases <<<"

# Check if scripts exist
if [ ! -f "$OPENCODE_ENV_PATH" ]; then
    echo "❌ Error: opencode-env.sh not found at $OPENCODE_ENV_PATH"
    exit 1
fi

if [ ! -f "$OPENCODE_PROFILE_PATH" ]; then
    echo "❌ Error: opencode-profile.sh not found at $OPENCODE_PROFILE_PATH"
    exit 1
fi

# Generate alias block
generate_aliases() {
    cat <<ALIASES
$ALIAS_BLOCK_START
# OpenCode multi-account management aliases
# Auto-generated by add-opencode-aliases.sh

# opencode-env.sh aliases (environment-based switching)
alias oe="$OPENCODE_ENV_PATH"
alias oel="$OPENCODE_ENV_PATH list"
alias oec="$OPENCODE_ENV_PATH create"
alias oee="$OPENCODE_ENV_PATH edit"
alias oes="$OPENCODE_ENV_PATH show"
alias oev="$OPENCODE_ENV_PATH validate"

# opencode-profile.sh aliases (full profile rotation)
alias op="$OPENCODE_PROFILE_PATH"
alias opl="$OPENCODE_PROFILE_PATH list"
alias opc="$OPENCODE_PROFILE_PATH create"
alias ops="$OPENCODE_PROFILE_PATH switch"
alias opcurrent="$OPENCODE_PROFILE_PATH current"
alias opedit="$OPENCODE_PROFILE_PATH edit"

# Quick run with specific accounts
alias oc-work="$OPENCODE_ENV_PATH work opencode"
alias oc-personal="$OPENCODE_ENV_PATH personal opencode"

$ALIAS_BLOCK_END
ALIASES
}

# Check if already exists
if grep -q "$ALIAS_BLOCK_START" "$ZSHRC" 2>/dev/null; then
    echo "⚠ Aliases already exist in $ZSHRC"
    echo "Do you want to update them? [y/N] "
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 0
    fi

    # Remove existing block
    if command -v sed &>/dev/null; then
        sed -i.bak "/$ALIAS_BLOCK_START/,/$ALIAS_BLOCK_END/d" "$ZSHRC"
        rm -f "${ZSHRC}.bak" 2>/dev/null || true
        echo "✅ Removed old aliases"
    fi
fi

# Add new block
echo "" >> "$ZSHRC"
generate_aliases >> "$ZSHRC"

echo ""
echo "✅ Added OpenCode aliases to $ZSHRC"
echo ""
echo "To use immediately, run:"
echo "  source ~/.zshrc"
echo ""
echo "Available aliases:"
echo "  oe          opencode-env.sh (all commands)"
echo "  op          opencode-profile.sh (all commands)"
echo ""
echo "For full list see: $ZSHRC"
